// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Y0ShGd7Mjxz9svgxQjXrJV_R-6agef8',
    appId: '1:748817817158:web:3c39884f50f62be3153447',
    messagingSenderId: '748817817158',
    projectId: 'e-commerce-29bef',
    authDomain: 'e-commerce-29bef.firebaseapp.com',
    storageBucket: 'e-commerce-29bef.firebasestorage.app',
    measurementId: 'G-52WB1BZ1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjptCAVsop362jnPa5Npk5H4LG23nwoTs',
    appId: '1:748817817158:android:535d20efa1693e8b153447',
    messagingSenderId: '748817817158',
    projectId: 'e-commerce-29bef',
    storageBucket: 'e-commerce-29bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuR4vd4ZNFo5Z7MNH27XDOW5lCMOdXnU',
    appId: '1:748817817158:ios:30f171c3159ff389153447',
    messagingSenderId: '748817817158',
    projectId: 'e-commerce-29bef',
    storageBucket: 'e-commerce-29bef.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
